version: '3.8'
services:
  laravel_app:
    build:
      context: ./php
    image: php:8.2-fpm-alpine
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ../src:/var/www
      - ./laravel/php.ini:/usr/local/etc/php/php.ini
    networks:
      - elk_network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - elk_network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - elk_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ../src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - laravel_app
    networks:
      - elk_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk_network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.2
    volumes:
      - ./elk/logstash/pipeline:/usr/share/logstash/pipeline
      - ../src/storage/logs:/usr/share/logstash/logs
    ports:
      - "5001:5000"
    depends_on:
      - elasticsearch
    networks:
      - elk_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk_network

volumes:
  elasticsearch_data:
  mysql_data:

networks:
  elk_network:
    driver: bridge
